# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b3fbe9031ef962152af23b1bf5615b893c54be4c1f0e34a7bdc63ec8006d25496009056c274922bbb221e7a302465797be65d5b79a0c421fb3fd2834aa6b5742

test:
  secret_key_base: 6a581cae86c81d073ff36dbecc2f74c11a6d928fdfb0095f50141216510c6d14805c36b067e9784a0119d171dc9371435bf41900c3e225744be5c382ca10853a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
